### ISSUE TITLE
SPI segfault

### ISSUE THREAD

**Issue by jgoeders** [byu-ecen-224-classroom/display#3]
https://github.com/byu-ecen-224-classroom/display/blob/dd40d176660f026e6d1f727c7b3024cada72b8a8/device.c#L31

When calling  `display_init()` I'm getting a segfault here.

**Comment by philipbl** [comment]
Did you use `sudo`?

**Comment by jgoeders** [comment]
Thanks!  That fixed it.  I can update the website.
